version : "3"
services:
  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: kidz
      MYSQL_PASSWORD: azaichi
      MYSQL_DATABASE: azaichi-kidz
    volumes:
      - ./build/src:/home/kidz/src
      - ./build/docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d